export default [
  'strapi::logger',
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          'connect-src': ["'self'", '*'],
          'img-src': ["'self'", 'data:', 'blob:', '*', 'http://*', 'https://*'],
          'media-src': ["'self'", 'data:', 'blob:', '*', 'http://*', 'https://*'],
          'default-src': ["'self'", '*'],
          'frame-src': ["'self'", '*'],
          'script-src': ["'self'", "'unsafe-inline'", "'unsafe-eval'", '*'],
          'style-src': ["'self'", "'unsafe-inline'", '*'],
          upgradeInsecureRequests: null,
        },
      },
      crossOriginEmbedderPolicy: false,
      crossOriginOpenerPolicy: false,
      crossOriginResourcePolicy: { policy: "cross-origin" },
      xssFilter: true,
      noSniff: true,
      frameGuard: true,
    },
  },
  {
    name: 'strapi::cors',
    config: {
      enabled: true,
      origin: '*',
      headers: ['*'],
      methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
      credentials: true,
      keepHeaderOnError: true,
      maxAge: 86400,
    },
  },
  'strapi::poweredBy',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
